' Gambas module file

''' This function provides a way for applications to creating compile errors.<br>
''' The script processing may be terminated when called.<br>
''' One of two things will happen:\
''' + If The halt parameter is true then an Error.raise() will halt the process.\
''' + Otherwise the error will be added to the error event queue and then control is returned to the calling program.\
''' \
''' Public Sub _Call(sPath As String, iLine As Integer, sMessage As String, [HaltCompile as boolean])

Export

'' Called by application to report an error and call error.raise<br>
'' Iline is the program line in error.<br>
'' sMessage is the message attached to the error being raised<br>
'' sPath is the path to the file containing the error
Public Sub _Call(sPath As String, iLine As Integer, sMessage As String, Optional HaltCompile As Boolean = True)

  Dim ErrorMessage As String = File.Name(Args[0]) & ": " & sPath & "." & iLine & ": " & sMessage

  If ScriptMain.$bRunAsPlugin Then
    ScriptCompileErrors[0] = ErrorMessage
  Endif

  If HaltCompile Then Error.Raise(ErrorMessage)

End ' Gambas module file

