' Gambas module file

''' This will configure the reader to apply an alias to the Script input line
''' Format is of each entry in this Collection.<br>
''' key is the Symbol value to be replace
''' value is the text to substitute in the collection.<br>
''' If an alias is found and the last two characters of the key are ()
''' then the line is checked for a following open brace
''' and every value separated by a comma, is substitutes into the value string
''' Up to a maximum of 20 parameters.<br>
''' Aliases will only be applied once but will try all others each time until all have been applied 
''' or there are no more matches.<br>
'''
''' * Examples<br>
''' Defined as:<br>
''' <p style = "margin-left: 40px">
''' <code>
'''    "SmallDog":"Animals.add(\"Dog\",\"Small\")"\
'''    "Animal()":"Animals.add(&1,&2)"\ 
''' </code></p><br>
''' in program looks like : \
''' <p style = "margin-left: 40px">
''' <code>
'''     Animal("dog","Big")\
'''     SmallDog\
''' </code></p><br>
''' After being applied looks like:\
''' <p style = "margin-left: 40px">
''' <code>
'''     Animals.add("Dog","Big")\
'''     Animals.add(\"Dog\",\"Small\")\
''' </code></p><br>
'''

Export 

'' Pass the provided alias list to the reader class.<br>
'' Causing this alias list to be applied to each line of the 
'' script being processed.
Public Sub _call(AliasList As Collection)
  If Not Class.IsLoaded("RegExp") Then 
    Try Component.Load("gb.pcre")
    If Error Then 
        Warning(("Component gb.pcre not found, filter will be ignored"))
        Return 
    Endif
    Try Class.Load("RegExp")
    If Error Then 
      Warning(("Unable to load regexp, filter will be ignored"))
      Return
    Endif
  Endif
  
  Reader.ScriptAlias = AliasList
  
End

